django_site/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django_site import settings
from myapp import views

urlpatterns = [
    path('', include('myapp.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
]

handler404 = views.page_not_found
admin.site.site_header = 'Панель администрирования'
admin.site.index_title = ''

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path, re_path, register_converter
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('explore-topics/', views.explore_topics, name='explore-topics'),
    path('contact/', views.contact, name='contact'),
    path('reviews/', views.reviews, name='reviews'),
    path('questionnaire/', views.questionnaire, name='questionnaire'),
    path('survey-thank-you/', views.survey_thank_you, name='survey_thank_you'),  # Страница успешной отправки
    path('admin/survey/<int:survey_id>/responses/', views.survey_responses_view, name='admin_survey_responses'),
    path('submit-request/', views.submit_request, name='submit_request'),
    path('lk/', views.lk, name='lk'),
    path('lk/grammar/', views.grammar_sections, name='grammar_sections'),
    path('lk/grammar/<int:section_id>/', views.grammar_materials, name='grammar_materials'),
    path('lk/homework/', views.homework_list, name='homework_list'),
    path('lk/homework/<int:homework_id>/submit/', views.submit_homework, name='submit_homework'),
    path('lk/completed-homework/', views.completed_homework, name='completed_homework'),

]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),

]

templates/base.html
{#<link type="text/css" href="{% static 'myapp/css/styles.css' %}" rel="stylesheet"/>#}

{#colors = #f6d0e1 (pink), #cfc2d3 (orchid), #6f5b98 (ultraviolet), #bed392 (lettuce green), #ede992 (yellow iris),#}
{# #f7b3a8 (peach), #3f3d54 (astral aura(dark)), #f3ebe1 (gardenia(bright))#}

{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'myapp/css/styles.css' %}">
    <!-- Подключение jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    {% block extra_styles %} {% endblock %}
</head>
<body>

<!-- Верхняя полоса с кнопками -->
<div class="top-bar">
    <a href="{% url 'home' %}" class="logo">NO PRESSURE</a>
    <!-- Кнопка для открытия модального окна -->
    <button class="openModal">Оставить заявку</button>
    <!-- Модальное окно -->
    <div id="consultationModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h2>Запись на консультацию</h2>
            <form id="consultationForm" data-url="{% url 'submit_request' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="name">Имя:</label>
                    <input type="text" id="name" name="name" class="styled-input" required>
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" id="email" name="email" class="styled-input" required>
                </div>
                <div class="form-group">
                    <label for="phone">Телефон или Telegram:</label>
                    <input type="tel" id="phone" name="phone" class="styled-input" required>
                </div>
                <div class="form-group">
                    <label for="message">Сообщение:</label>
                    <textarea id="message" name="message" class="styled-input"></textarea>
                </div>
                <button type="submit">Отправить</button>
            </form>
        </div>
    </div>
    <a href="{% url 'lk' %}">Личный кабинет</a>
</div>

<!-- Основной контент -->
<div class="container">
    {% block content %}
    {% endblock %}
</div>
<script src="{% static 'myapp/js/modal.js' %}"></script>
{% block extra_js %} {% endblock %}
</body>
</html>

templates/base_lk.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'myapp/css/styles_lk.css' %}">
    <!-- Подключение jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <style>
    </style>
    {% block extra_styles %} {% endblock %}
</head>
<body>

<!-- Верхняя полоса с кнопками -->
<div class="top-bar">
    <a href="{% url 'home' %}" class="logo">NO PRESSURE</a>
    <!-- Кнопка для открытия модального окна -->
    <button class="openModal">Оставить заявку</button>
    <!-- Модальное окно -->
    <div id="consultationModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h2>Запись на консультацию</h2>
            <form id="consultationForm" data-url="{% url 'submit_request' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="name">Имя:</label>
                    <input type="text" id="name" name="name" class="styled-input" required>
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" id="email" name="email" class="styled-input" required>
                </div>
                <div class="form-group">
                    <label for="phone">Телефон или Telegram:</label>
                    <input type="tel" id="phone" name="phone" class="styled-input" required>
                </div>
                <div class="form-group">
                    <label for="message">Сообщение:</label>
                    <textarea id="message" name="message" class="styled-input"></textarea>
                </div>
                <button type="submit">Отправить</button>
            </form>
        </div>
    </div>

    <a href="{% url 'lk' %}">Личный кабинет</a>
</div>

<!-- Боковая полоса с кнопками -->
<div class="sidebar">
    <ul>
        <li><a href="{% url 'grammar_sections' %}">Материалы по грамматике</a></li>
        <li><a href="{% url 'homework_list' %}">Домашние задания</a></li>
        <li><a href="{% url 'completed_homework' %}">Выполненные домашние задания</a></li>
        <li><a href="{% url 'users:profile' %}">Мой профиль</a></li>
        <li><a href="{% url 'users:logout' %}">Выйти из учётной записи</a></li>
    </ul>
</div>

<!-- Контент страницы -->
<div class="container">
    <h1>{{ title }}</h1>
    <!-- Сообщения -->
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="alert {{ message.tags }}">{{ message|safe }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    {% block content %}
        <!-- Динамический контент страницы -->
    {% endblock %}
</div>

<!-- Скрипты -->
<script src="{% static 'myapp/js/modal.js' %}"></script>
{% block extra_js %} {% endblock %}

</body>
</html>